INSERT INTO `db309amb4`.`User_Table` (`User_ID`, `First_Name`, `Last_Name`, `Email_Address`, `Height`, `Weight`, `Age`, `BirthDate`, `Loss_Goal`, `Workout_Plan_ID`, `Assigned_Trainer_ID`, `IsTrainer`, `IsAdmin`, `Username`, `Passwordd`) VALUES ('3', 'Justin', 'Bader', 'Jbader@iastate.edu', '70', '240', '22', '1995-06-23', '10', '0', '0', '0', '1', 'Holy', 'Cow');
INSERT INTO `db309amb4`.`User_Table` (`User_ID`, `First_Name`, `Last_Name`, `Email_Address`, `Height`, `Weight`, `Age`, `BirthDate`, `Loss_Goal`, `Workout_Plan_ID`, `Assigned_Trainer_ID`, `IsTrainer`, `IsAdmin`, `Username`, `Passwordd`) VALUES ('4', 'Will', 'Emory', 'Whemory@iastate.edu', '40', '200', '20', '1993-03-01', '0', '0', '0', '0', '0', 'Step', 'Pets');
INSERT INTO `db309amb4`.`User_Table` (`User_ID`, `First_Name`, `Last_Name`, `Email_Address`, `Height`, `Weight`, `Age`, `BirthDate`, `Loss_Goal`, `Workout_Plan_ID`, `Assigned_Trainer_ID`, `IsTrainer`, `IsAdmin`, `Username`, `Passwordd`) VALUES ('5', 'Sally', 'Trainer', 'Trainer@gmail.com', '50', '100', '20', '1990-09-06', '0', '0', '0', '1', '0', 'Blank', 'White');
INSERT INTO `db309amb4`.`User_Table` (`User_ID`, `First_Name`, `Last_Name`, `Email_Address`, `Height`, `Weight`, `Age`, `BirthDate`, `Loss_Goal`, `Workout_Plan_ID`, `Assigned_Trainer_ID`, `IsTrainer`, `IsAdmin`, `Username`, `Passwordd`) VALUES ('6', 'Admin', 'Admin', 'Admin@gmail.com', '99', '99', '99', '1989-10-09', '0', '0', '0', '0', '1', 'Password', 'Username');


INSERT INTO `db309amb4`.`Workout_Plan` (`Workout_Plan_ID`, `Monday_Description`, `Monday_Workout`, `Tuesday_Description`, `Tuesday_Workout`, `Wednesday_Description`, `Wednesday_Workout`, `Thursday_Description`, `Thursday_Workout`, `Friday_Description`, `Friday_Workout`, `Saturday_Description`, `Saturday_Workout`, `Sunday_Description`, `Sunday_Workout`) VALUES ('0', 'Werking on Monday', '2x Deadlift:3x Squats', 'Werking on Tuesday', '4x Kleen:10x Jumps', 'Werking on Wednesday', '5x Walks', 'Werking on Thursday', '2x Bloops', 'Werking on Friday', '7x Blops', 'Werking on Saturday', '10x jloops', 'Werking on Sunday', '55x claps');
INSERT INTO `db309amb4`.`Workout_Plan` (`Workout_Plan_ID`, `Monday_Description`, `Monday_Workout`, `Tuesday_Description`, `Tuesday_Workout`, `Wednesday_Description`, `Wednesday_Workout`, `Thursday_Description`, `Thursday_Workout`, `Friday_Description`, `Friday_Workout`, `Saturday_Description`, `Saturday_Workout`, `Sunday_Description`, `Sunday_Workout`) VALUES ('1', 'Werking on Monday 1', '4x Kleen:10x Jumps', 'Werking on Tuesday1', '2x Deadlift:3x Squats', 'Werking on Wednesday 1', '2x Bloops', 'Werking on Thursday 1', '5x Walks', 'Werking on Friday 1', '10x jloops', 'Werking on Saturday 1', '7x Blops', 'Werking on Sunday 1', '55x boos');
INSERT INTO `db309amb4`.`Workout_Plan` (`Workout_Plan_ID`, `Monday_Description`, `Monday_Workout`, `Tuesday_Description`, `Tuesday_Workout`, `Wednesday_Description`, `Wednesday_Workout`, `Thursday_Description`, `Thursday_Workout`, `Friday_Description`, `Friday_Workout`, `Saturday_Description`, `Saturday_Workout`, `Sunday_Description`, `Sunday_Workout`) VALUES ('2', 'Werking on Monday 2', '55x boos', 'Werking on Tuesday2', '5x Walks', 'Werking on Wednesday 2', '4x Kleen:10x Jumps', 'Werking on Thursday 2', '55x boos', 'Werking on Friday 2', '7x Blops', 'Werking on Saturday 2', '4x Kleen:10x Jumps', 'Werking on Sunday 2', '10x jloops');

INSERT INTO `db309amb4`.`Workout_Plans` (`Workout_Plan_ID`, `Plan_Name`, `Plan_Description`) VALUES ('0', 'Hardcore', 'Gets dem gainz good');
INSERT INTO `db309amb4`.`Workout_Plans` (`Workout_Plan_ID`, `Plan_Name`, `Plan_Description`) VALUES ('1', 'Softcore', 'Gets dem gains poor');
INSERT INTO `db309amb4`.`Workout_Plans` (`Workout_Plan_ID`, `Plan_Name`, `Plan_Description`) VALUES ('2', 'Mediumcore', 'Gets dem gains ok');